### ISSUE TITLE
problem with demo03 and demo04

### ISSUE THREAD

**Issue by dlethin** [pvdissel/talk-jenkins-jobdsl#3]
After working around a previous issue and upgrading to jobdsl to 1.29, I'm able to proceed further with the command line build.  However, I've run into two other problems:

1 - One of the jobs being generated is failing.  Not sure if it supposed to.  Also not sure if that is related to the change I made to upgrade to 1.29 --

<pre>
:demos/01-few-jobs:clean UP-TO-DATE
:demos/02-lots-of-jobs:clean UP-TO-DATE
:demos/03-ci++-setup:clean UP-TO-DATE
:demos/04-cd-setup:clean
:demos/05-live:clean UP-TO-DATE
:demos/01-few-jobs:prepareJobDslWorkspace
:demos/01-few-jobs:generateJenkinsJobs
:demos/02-lots-of-jobs:prepareJobDslWorkspace
:demos/02-lots-of-jobs:generateJenkinsJobs
Processing DSL script /Users/dlethin/bld/github/talk-jenkins-jobdsl/demos/02-lots-of-jobs/build/jobDsl/workspace/demo-02.dsl.groovy
:demos/03-ci++-setup:compileJava UP-TO-DATE
:demos/03-ci++-setup:compileGroovy
:demos/03-ci++-setup:processResources UP-TO-DATE
:demos/03-ci++-setup:classes
:demos/03-ci++-setup:compileTestJava UP-TO-DATE
:demos/03-ci++-setup:compileTestGroovy
:demos/03-ci++-setup:processTestResources
:demos/03-ci++-setup:testClasses
:demos/03-ci++-setup:test
:demos/03-ci++-setup:check
:demos/03-ci++-setup:prepareJobDslWorkspace
:demos/03-ci++-setup:generateJenkinsJobs
ScriptSettings are set to [[]]
-------------------------------------------------
Running jobDsl for [Projects] in lifeCycle [TEST]
Starting groovy DSL for [TEST] lifeCycle...
Generating job [CreateProjectJobs] with type [BuildFlow]                   ERROR
!! Cannot access first() element from an empty List
tld.company.taxp.view.AppViewsCreator$_createNestedViewForAppCollection_closure3.doCall(AppViewsCreator.groovy:38)

--------------------------------------------------------------
Running jobDsl for [Test Automation Flows] in lifeCycle [TEST]
Generating job [Flow_Deploy_Daily] with type [BuildFlow]                   SUCCESS

Generating job [Flow_Deploy_Evening] with type [BuildFlow]                 SUCCESS

Generating job [Flow_Deploy_Nightly] with type [BuildFlow]                 SUCCESS

-------------------------------------------------------
Running jobDsl for [Sprint Hopping] in lifeCycle [TEST]
Generating job [SprintHopping_Create_Branch_From_Last_Stable_Tag] with type [BuildFlow] SUCCESS

Generating job [SprintHopping_Auto_Create_Branch] with type [Freeform]     SUCCESS

:demos/03-ci++-setup:generateJenkinsJobs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':demos/03-ci++-setup:generateJenkinsJobs'.
> There was an error during the creation of [1] job(s)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.403 secs
[CMBL1291628b1:~/bld/github/talk-jenk
</pre>

2 - demo04 is failing to build.

Since demo03 fails above, in the top-level gradle build, I tried to build demo04 directly, but also run into an error:

<pre>
./gradlew :demos/04-cd-setup:generateJenkinsJobs
:demos/04-cd-setup:prepareJobDslWorkspace
:demos/04-cd-setup:generateJenkinsJobs
yo3
Deploying 'uk' to host 'deployer@10.0.0.115
:demos/04-cd-setup:generateJenkinsJobs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':demos/04-cd-setup:generateJenkinsJobs'.
> java.io.IOException: Unable to run script

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':demos/04-cd-setup:generateJenkinsJobs'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnResult.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:45)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator.runCommand(DaemonStateCoordinator.java:258)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy.doBuild(StartBuildOrRespondWithBusy.java:49)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.HandleCancel.execute(HandleCancel.java:36)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.HandleStop.execute(HandleStop.java:30)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.CatchAndForwardDaemonFailure.execute(CatchAndForwardDaemonFailure.java:32)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
    at org.gradle.launcher.daemon.server.exec.DefaultDaemonCommandExecuter.executeCommand(DefaultDaemonCommandExecuter.java:52)
    at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.handleCommand(DefaultIncomingConnectionHandler.java:154)
    at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.receiveAndHandleCommand(DefaultIncomingConnectionHandler.java:128)
    at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.run(DefaultIncomingConnectionHandler.java:116)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.internal.UncheckedException: java.io.IOException: Unable to run script
    at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:39)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:66)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 69 more
Caused by: java.io.IOException: Unable to run script
    at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngineForParent(DslScriptLoader.java:74)
    at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngine(DslScriptLoader.java:89)
    at javaposse.jobdsl.dsl.DslScriptLoader$runDslEngine.call(Unknown Source)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask.processDslScript(GenerateConfigsTask.groovy:96)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask$_processJobDslFiles_closure2.doCall(GenerateConfigsTask.groovy:73)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask.processJobDslFiles(GenerateConfigsTask.groovy:72)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask.this$4$processJobDslFiles(GenerateConfigsTask.groovy)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask$this$4$processJobDslFiles$0.callCurrent(Unknown Source)
    at nl.ikoodi.gradle.plugin.jenkins.jobdsl.tasks.GenerateConfigsTask.compileAction(GenerateConfigsTask.groovy:39)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    ... 76 more
Caused by: java.io.FileNotFoundException: /Users/dlethin/bld/github/talk-jenkins-jobdsl/demos/04-cd-setup/build/jobDsl/workspace/src/main/groovy/helperscripts/releaseProject.groovy (No such file or directory)
    at javaposse.jobdsl.dsl.FileJobManagement.readFileInWorkspace(FileJobManagement.groovy:77)
    at javaposse.jobdsl.dsl.JobManagement$readFileInWorkspace$0.call(Unknown Source)
    at javaposse.jobdsl.dsl.JobParent.readFileFromWorkspace(JobParent.groovy:90)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5_closure30.doCall(app-develop.dsl.groovy:92)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5_closure30.doCall(app-develop.dsl.groovy)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper.executeInContext(AbstractContextHelper.groovy:21)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$executeInContext$0.callStatic(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$executeInContext$0.callStatic(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper.execute(AbstractContextHelper.groovy:32)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$execute.callCurrent(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$execute.callCurrent(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper.steps(StepContextHelper.groovy:19)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper$steps.call(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper$steps.call(Unknown Source)
    at javaposse.jobdsl.dsl.Job.steps(Job.groovy)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5.doCall(app-develop.dsl.groovy:90)
    at javaposse.jobdsl.dsl.JobParent.job(JobParent.groovy:32)
    at javaposse.jobdsl.dsl.JobParent.job(JobParent.groovy)
    at javaposse.jobdsl.dsl.DslFactory$job.callCurrent(Unknown Source)
    at app-develop.dsl.createApplicationDevelopPipeLine(app-develop.dsl.groovy:79)
    at app-develop.dsl$_run_closure1.doCall(app-develop.dsl.groovy:58)
    at app-develop.dsl.run(app-develop.dsl.groovy:56)
    at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngineForParent(DslScriptLoader.java:69)
    ... 85 more

BUILD FAILED

Total time: 6.565 secs

</pre>

Is there some expectation that src/main/groovy will be copied over to the build/jobDsl/workspace directory?  I don't see any provisions for that in the build.gradle file.

BTW, I feel a bit petty logging these as issues -- please know I'm very grateful you took the time to contribute and share the work in this repository.  It is very helpful and kind of you.

Cheers.

Doug

**Comment by dlethin** [comment]
I at least figured out the issue with demo03 -- it works if run gradle directly in the demos/03-ci++-setup directory but it doesn't work when when running at the top level directory.  The issue is that it's trying to find an "appconfigs" dir at the current directory which obviously doesn't exist.

I did run into the same issue that I reported in #2 , but applied the same proposed fix to the build.gradle file and was successful.

**Comment by pvdissel** [comment]
> BTW, I feel a bit petty logging these as issues -- please know I'm very grateful you took the time to contribute and share the work in this repository. It is very helpful and kind of you.

Not problem, this is good. By logging these issues I know that all this is atleast useful to someone :smile: And, fixing any errors and getting things to work on Mac only makes this repo better. So :+1: for logging these issues, and help solving them.

So, just to have it clear. Demo03 is completely working now for you? As long as you run the build from the demo03 project directory?

And how about demo04?

**Comment by dlethin** [comment]
OK, here is the output of gradle with --stacktrace option when running in the demos/04-cd-setup directory:

<pre>
Caused by: java.io.FileNotFoundException: /Users/dlethin/bld/github/talk-jenkins-jobdsl/demos/04-cd-setup/build/jobDsl/workspace/src/main/groovy/helperscripts/releaseProject.groovy (No such file or directory)
    at javaposse.jobdsl.dsl.FileJobManagement.readFileInWorkspace(FileJobManagement.groovy:77)
    at javaposse.jobdsl.dsl.JobManagement$readFileInWorkspace$0.call(Unknown Source)
    at javaposse.jobdsl.dsl.JobParent.readFileFromWorkspace(JobParent.groovy:90)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5_closure30.doCall(app-develop.dsl.groovy:92)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5_closure30.doCall(app-develop.dsl.groovy)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper.executeInContext(AbstractContextHelper.groovy:21)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$executeInContext$0.callStatic(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$executeInContext$0.callStatic(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper.execute(AbstractContextHelper.groovy:32)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$execute.callCurrent(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.AbstractContextHelper$execute.callCurrent(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper.steps(StepContextHelper.groovy:19)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper$steps.call(Unknown Source)
    at javaposse.jobdsl.dsl.helpers.step.StepContextHelper$steps.call(Unknown Source)
    at javaposse.jobdsl.dsl.Job.steps(Job.groovy)
    at app-develop.dsl$_createApplicationDevelopPipeLine_closure5.doCall(app-develop.dsl.groovy:90)
    at javaposse.jobdsl.dsl.JobParent.job(JobParent.groovy:32)
    at javaposse.jobdsl.dsl.JobParent.job(JobParent.groovy)
    at javaposse.jobdsl.dsl.DslFactory$job.callCurrent(Unknown Source)
    at app-develop.dsl.createApplicationDevelopPipeLine(app-develop.dsl.groovy:79)
    at app-develop.dsl$_run_closure1.doCall(app-develop.dsl.groovy:58)
    at app-develop.dsl.run(app-develop.dsl.groovy:56)
    at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngineForParent(DslScriptLoader.java:69)
    ... 85 more
</pre>

The app-develop.dsl.groovy script has the following jobdsl code:

<pre>
   ...
    steps {
            shell addPreBuildShellStep(config)
            groovyCommand(readFileFromWorkspace('src/main/groovy/helperscripts/releaseProject.groovy'), config.groovyVersion) {
                scriptParam('--minor')
            }
        }
   ...
</pre>

The issue I guess seem to be when running via gradle, the workspace is running out ./build/jobsdsl, but when running out of jenkins the workspace is .    When running from command gradle command line locally, it looking for the releaseProject in following path:

<pre>
./build/jobDsl/workspace/src/main/groovy/helperscripts/releaseProject.groovy
</pre>

but its actually in the following path:

<pre>
./build/jobDsl/workspace/helperscripts/releaseProject.groovy
</pre>

**Comment by pvdissel** [comment]
Hey Doug, thanks again :smile: 

I've released a new version of gradle-jenkins-jobdsl, [v0.1.6](https://github.com/pvdissel/gradle-jenkins-jobdsl/releases/tag/v0.1.6), which fixes the readFileFromWorkspace issue.
Just wait for it to be picked up by the Gradle plugin portal:
- http://plugins.gradle.org/plugin/nl.ikoodi.jenkins.jobdsl

About #2, releasing new versions with support for the newer JobDSL versions will take me some more time, I hope to get that done later this week. Again, sorry for the delay.

**Comment by pvdissel** [comment]
After v0.1.6 appears in the Gradle plugin portal, I will apply the new version to this talk-jenkins-jobdsl repository
